version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .docker_app_env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"